version: "3"
services:
  #### Innestől a sajátom
  gateway:
    build: ./
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      smartpot_network:
        ipv4_address: 172.16.0.2
  ######################
  # Setup mongodb container
  ######################
  mongodb:
    build: ./extra/docker/mongo_docker
    restart: always
    networks:
      smartpot_network:
        ipv4_address: 172.16.0.3
    #image: "mongo"
    ports:
      -   "27017:27017"
    environment:
      -  DEFAULT_USERNAME=${ENV_DEFAULT_USERNAME}
      -  DEFAULT_PASSWORD=${ENV_DEFAULT_PASSWORD}
  mosquitto:
    build: ./extra/docker/mosquitto_docker
    restart: always
    networks:
      smartpot_network:
        ipv4_address: 172.16.0.4
    ports:
      -   "1883:1883"
      -   "9001:9001"
  filebrowser:
    build: ./extra/filebrowser
    restart: always
    networks:
      smartpot_network:
        ipv4_address: 172.16.0.5
    ports:
      -   "80:80"
    volumes:
      -   ./extra/filebrowser/Program-core:/var/www/html
      -   ./extra/filebrowser/Pictures:/var/www/html/files

networks:
  smartpot_network:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.0.0/24