version: "3"
services:
  #### Innestől a sajátom
  ######################
  # Setup mongodb container
  ######################
  mongodb:
    build: ./extra/docker/mongo_docker
    restart: always
    #image: "mongo"
    ports:
      -   "27017:27017"
    environment:
      -  DEFAULT_USERNAME = "admin"
      -  DEFAULT_PASSWORD = "admin"